In [5]:
import os

os.getcwd() #identify the current directory
os.listdir() #list all the files in the current directory

['.ipynb_checkpoints',
 'Customer Shopping Behaviour Analysis.ipynb',
 'customer_shopping_behavior.csv']

In [2]:
import pandas as pd

df = pd.read_csv('customer_shopping_behavior.csv') #importing csv file as a dataframe

In [11]:
df.head() #displays upper 5 rows

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [12]:
df.tail() #displays lower 5 rows

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [16]:
df.info() #describes the structure of the dataframe (rows, columns, data type of each column, etc)

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [17]:
df.describe() #only describes numerical columns

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [18]:
df.describe(include = 'all') #describes both numerical and categorical columns

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [19]:
df.isnull() #display all rows, if a value is null, it will appear as True

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3896,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3897,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3898,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3899,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [22]:
df.isnull().sum() #summarises the number of null values in each column
#As we can see there are 37 null values for Review Rating. We must decide how to resolve the issue of these null values. 
#We may decide to delete the rows with these null values or impute them with an appropriate value.
#We may decide to impute the null values with the mean or the median of the column.
#Mean may not be appropriate as it may be skewed by outliers.
#Median may be appropriate as it may be robust to outliers.
#The null values may be imputed with the overall median, however this may introduce bias into the data.
#The reason for this is that the reviews can be segmented by the category (such as clothing and footwear), and the ratings within each category may vary significantly.
#Therefore, if all the null values are imputed with the overall medium for the column, this may suggest that the footwear review ratings should have the same median for the null values as the clothing review rating.
#This may introduce bias into the dataset.
#Instead the null values for the Review Ratings in each category may be imputed with the the median review rating for each category.
#Therefore if a clothing item is missing a review rating, it is imputed with the median review rating for clothing specifically, instead of the overall median or the median review rating of footwear.

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [35]:
df.groupby('Category') 
#df.groupby functions similary to GROUP BY in SQL. It is necessary to perform aggregate functions on certain subsets or groups of data.
#For example, in SQL, to determine the mean of review ratings alone with other columns you would GROUP BY the other columns then execute AVG(Review Ratings)
#Likewise in Python we can group data by category and perform aggregate functions on them.

In [6]:
df['Review Rating'].describe() #Describes summary statistics of just Review Ratings.

count    3863.000000
mean        3.750065
std         0.716983
min         2.500000
25%         3.100000
50%         3.800000
75%         4.400000
max         5.000000
Name: Review Rating, dtype: float64

In [9]:
df.groupby('Category')['Review Rating'].describe() 
#Groups the entire dataset by the category column. Selects the Review Rating column from the grouped dataset. Then describes the summary statistics of Review Ratings grouped by category.

              count      mean       std  min  25%  50%  75%  max
Category
Accessories  1229.0  3.769976  0.716080  2.5  3.2  3.8  4.4  5.0
Clothing     1718.0  3.721537  0.718595  2.5  3.1  3.7  4.3  5.0
Footwear      594.0  3.793771  0.719222  2.5  3.2  3.8  4.4  5.0
Outerwear     322.0  3.745652  0.704323  2.5  3.1  3.8  4.3  5.0

In [14]:
df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))
#Group the dataset by category. Select the Review Rating Column. Transform this column (temporarily named x) by imputing all null values with the median values of the column.
#The lambda and x is mostly to define a temporary short function, and may be considered syntax related for the purposes of the transformation.

0       3.1
1       3.1
2       3.1
3       3.5
4       2.7
       ...
3895    4.2
3896    4.5
3897    2.9
3898    3.8
3899    3.1
Name: Review Rating, Length: 3900, dtype: float64

In [19]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median())) 
#Fill all null values in the Review Rating column by the median Review Rating associated with the corresponding category for the row.

In [20]:
df.isnull().sum() #Examining for any remaining null values.
#No null values detected.

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [27]:
df.columns #Displays all the column names in the dataframe.

Index(['customer id', 'age', 'gender', 'item purchased', 'category',
       'purchase amount (usd)', 'location', 'size', 'color', 'season',
       'review rating', 'subscription status', 'shipping type',
       'discount applied', 'promo code used', 'previous purchases',
       'payment method', 'frequency of purchases'],
      dtype='str')

In [28]:
#It may be considered good practice to rename columns that may may include spaces to snakecase. This may reduce programming and syntax errors.
df.columns = df.columns.str.lower() #Convert all column names to lower case.
df.columns

Index(['customer id', 'age', 'gender', 'item purchased', 'category',
       'purchase amount (usd)', 'location', 'size', 'color', 'season',
       'review rating', 'subscription status', 'shipping type',
       'discount applied', 'promo code used', 'previous purchases',
       'payment method', 'frequency of purchases'],
      dtype='str')

In [31]:
df.columns = df.columns.str.replace(' ', '_') #Replace all spaces (' ') in column names with an underscore ('_')
df.columns #All column names are in snakecase. Though purchase_amount_(usd) may be improved.

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [35]:
df.rename(columns = {'purchase_amount_(usd)':'purchase_amount'}) #Replace the purchase_amount_(usd) column name with purchase_amount. Returns the resuling dataframe.

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [41]:
df = df.rename(columns = {'purchase_amount_(usd)':'purchase_amount'}) #Replace the purchase_amount_(usd) column name with purchase_amount.
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [42]:
df['age'].head(5) #There may be another column associated with age. Organising the ages into age groups such as Young Adult, Adult, Middle-Agged, and Senior

0    55
1    19
2    50
3    21
4    45
Name: age, dtype: int64

In [49]:
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior'] #Create a list of age group labels.

np.int64(70)

In [51]:
pd.qcut(df['age'], q = 4, labels = labels) #Selects the age column in the dataframe. Sorts the ages into four quartile groups (25%, 50%, 75%, 100%). Then assigns each quartile group with the corresponding label in the labels list earlier.

0       Middle-aged
1       Young Adult
2       Middle-aged
3       Young Adult
4       Middle-aged
           ...
3895          Adult
3896    Middle-aged
3897    Middle-aged
3898          Adult
3899    Middle-aged
Name: age, Length: 3900, dtype: category
Categories (4, str): ['Young Adult' < 'Adult' < 'Middle-aged' < 'Senior']

In [54]:
df['age_group'] = pd.qcut(df['age'], q = 4, labels = labels) #Assigns age group labels for each age.
df[['age', 'age_group']].head(10) #Displays the upper 10 rows of age and age_group.
#Age group labels seem appropriate.

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [59]:
df['frequency_of_purchases'].unique() #Displays a list of unique values in the frequency_of_purchases column in the dataframe.

<StringArray>
[   'Fortnightly',         'Weekly',       'Annually',      'Quarterly',
      'Bi-Weekly',        'Monthly', 'Every 3 Months']
Length: 7, dtype: str

In [64]:
#It may be of utility to create a new column to represent the categorical values in the frequency_of_purchases column as numerical values that represent the number of days between purchases.
frequency_mapping = {'Fortnightly': 14,
                     'Weekly': 7,
                     'Annually': 365,
                     'Quarterly': 90,
                     'Bi-Weekly': 14,
                     'Monthly': 30,
                     'Every 3 Months': 90} #Creates a dictionary with numerical assignments (in days) for every unique purchase frequency type. Some frequency types are equivalent such as quarterly and Every 3 Months (equivalent to approximately 90 days).
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping) #Creates a new column called purchase_frequency_days. This column contains the numerical representation (in days) of the frequency_of_purchases column in the same row.
df[['frequency_of_purchases', 'purchase_frequency_days']].head(10) #Displays the upper 10 rows of both 'frequency_of_purchases' and 'purchase_frequency_days' columns.
#The numerical assignments for each type of frequency_of_purchases appears appropriate.

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365
5                 Weekly                        7
6              Quarterly                       90
7                 Weekly                        7
8               Annually                      365
9              Quarterly                       90

In [67]:
df[['discount_applied', 'promo_code_used']].head() #While a discount that is applied may not be from a promo code, if these two columns are equivalent in values, then one column may be considered as redundant.

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes

In [68]:
df['discount_applied'] == df['promo_code_used'] #Identifying rows where both columns are equivalent in value.

0       True
1       True
2       True
3       True
4       True
        ...
3895    True
3896    True
3897    True
3898    True
3899    True
Length: 3900, dtype: bool

In [72]:
(df['discount_applied'] == df['promo_code_used']).all() #Determining if both columns are equivalent in value.
#The result is True.
#Therefore one of the columns may be considered to be redundant. promo_code_used may be removed.

np.True_

In [93]:
df = df.drop('promo_code_used', axis = 1) #Deletes the promo_code_used column in the dataframe and returns the resulting dataframe.
#axis = 1 specifies that it is a column that we desire to remove. axis = 0 refers to a row/index that we may desire to remove.
#Error may be due to the promo_code_used column being deleted already and the code being executed redundantly.

KeyError: "['promo_code_used'] not found in axis"

In [92]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365

In [94]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [97]:
#Installing psycopg2-binary, and sqlalchemy. These may be required to connect this Jupyter Notebook with a PGAdmin4 PostgreSQL server database named customer_behaviour.

In [98]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp311-cp311-win_amd64.whl.metadata (5.1 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.48-cp311-cp311-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.3.2-cp311-cp311-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\TheEm\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp311-cp311-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   --------------- ------------------------ 1.0/2.7 MB 10.1 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 9.2 MB/s  0:00:00
Downloading sqlalchemy-2.0.48-cp311-cp311-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------- ----- 1.8/2.1 MB 9.2 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 8.6 MB/s  0:00:00
Downloading greenlet-3.3.2-cp311-cp311-win_amd64.whl (230 kB)
Installing collected packages: psycopg2-binary, greenlet, sqlalchemy

   ---------------------------------------- 0/3 [psycopg2-binary]
   ---------------------------------------- 0/3 [psycopg2-binary]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.3.2 psycopg2-binary-2.9.11 sqlalchemy-2.0.48
Note: you may need to restart the kernel to use updated packages.

In [106]:
#This code may assist in establishing connection with PostgreSQL.
from sqlalchemy import create_engine #This function may be required to connect pandas to the PostgreSQL database table.

#Step 1: Connect to PostgreSQL
#Replace placeholders with your actual details
#To confirm actual details, you can access PGAdmin4 -> Server -> Right Click on PostgreSQL 18 -> Properties -> Connection
username ='postgres' #default user
password = 'password' #the password you set during the installation of PostgreSQL
host = 'localhost' #localhost may be utilised if operating locally
port = '5432' #default PostgreSQL port
database = 'customer_behaviour' #the database created in pgAdmin4, named customer_behaviour

engine = create_engine(f'postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}') 
#Creates an engine object with an f string. This f string is a URL to the database.
#postgresql+psycopg2 may suggest that the postgresql dialect may be utilised. psycopg2 may be the Python driver, which may be a library that communicates with PostgreSQL.
#engine is then the variable that may be utilised in pandas functions like df.to_sql("table_name", engine) to execute queries or supply data.

#Step 2: Load Dataframe into PostgreSQL
table_name = 'customer' #Any table name may be elected.
df.to_sql(table_name, engine, if_exists = 'replace', index = False)
#df.to_sql Sends the rows of the pandas dataframe to the database as a table.
#table_name is the name of the table in the PostgreSQL database
#The engine contains the PostgreSQL connection details and may be utilised as the connection destination.
#if_exists = 'replace' may replace any existing table_name with a recreated table_name with rows from the dataframe.
#index = False prevents pandas from generating a new column in the SQL table for the dataframe's index. This may ensure that only the original dataframe's columns may be utilised.

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")
#May print: Data successfully loaded into table 'customer' in database 'customer_behaviour'.
#Verify if the code may have executed successfully in pgAdmin4. Servers -> PostgreSQL 18 -> Databases -> customer_behaviour -> Schemas -> public -> Tables -> customer.
#customer is the table that may be used to execute SQL queries.

Data successfully loaded into table 'customer' in database 'customer_behaviour'.

In [ ]:
#This code below may assist in establishing a connection with MySQL
#Note: For pip commands, the code may not execute if there may be no ! before pip.

In [107]:
!pip install pymysql sqlalchemy

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: sqlalchemy in C:\Users\TheEm\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.0.48)
Requirement already satisfied: greenlet>=1 in C:\Users\TheEm\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\TheEm\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [124]:
from sqlalchemy import create_engine
import pymysql

#MySQL connection
username = 'root'
password = '*****'
host = 'localhost'
port = '3306'
database = 'mydatabase' #Ensure that there is a schema named mydatabase in MySQL. If there is no schema named mydatabase in MySQL, it may be created in MySQL in Schemas.

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

#Write dataframe to MySQL
table_name = 'mytable' #choose any table name
df.to_sql(table_name, engine, if_exists = 'replace', index = False)

#Read back sample
pd.read_sql('SELECT * FROM mytable LIMIT 5;', engine)
#This connection may appear to be successful.

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365

In [111]:
!mysql -u root -p -h localhost -P 3306 mydatabase

'mysql' is not recognized as an internal or external command,
operable program or batch file.